# Generated by Django 5.1.5 on 2025-02-23 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boib_scraper", "0004_alter_anuncioboib_numero_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnuncioBoibProcesado",
            fields=[
                (
                    "anuncio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="boib_scraper.anuncioboib",
                        to_field="numero_url",
                    ),
                ),
                ("entidad_convocante", models.CharField(max_length=255)),
                ("isla", models.CharField(max_length=50)),
                ("numero_anuncio", models.CharField(max_length=50)),
                ("cuerpo_trabajo", models.JSONField()),
                ("numero_plazas", models.JSONField()),
                ("grupo_profesional", models.JSONField()),
                ("tipo_proceso", models.CharField(max_length=50)),
                ("fase_proceso", models.CharField(max_length=50)),
                ("requisitos", models.JSONField()),
                ("plazo_presentacion", models.JSONField()),
                ("fecha_publicacion", models.DateField()),
                ("fecha_maxima_presentacion", models.DateField()),
            ],
            options={
                "db_table": "anuncios_boib_IA",
            },
        ),
    ]
