# Generated by Django 5.1.5 on 2025-02-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procesador_IA", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anuncioboibprocesado",
            name="cuerpo_trabajo",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anuncioboibprocesado",
            name="fecha_maxima_presentacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anuncioboibprocesado",
            name="fecha_publicacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anuncioboibprocesado",
            name="grupo_profesional",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anuncioboibprocesado",
            name="numero_anuncio",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="anuncioboibprocesado",
            name="numero_plazas",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anuncioboibprocesado",
            name="plazo_presentacion",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anuncioboibprocesado",
            name="requisitos",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
