# Generated by Django 5.1.5 on 2025-02-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procesador_IA", "0002_alter_anuncioboibprocesado_cuerpo_trabajo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anuncioboibprocesado",
            name="link_html",
            field=models.URLField(blank=True, null=True),
        ),
    ]
