# Generated by Django 5.1.5 on 2025-02-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procesador_IA", "0003_anuncioboibprocesado_link_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="anuncioboibprocesado",
            name="tipo_personal",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="anuncioboibprocesado",
            name="tipo_turno",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="anuncioboibprocesado",
            name="fase_proceso",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="anuncioboibprocesado",
            name="tipo_proceso",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
