# Generated by Django 5.1.5 on 2025-02-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boib_scraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anuncioboib",
            name="administracion",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="anuncioboib",
            name="entidad",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="anuncioboib",
            name="link_html",
            field=models.URLField(max_length=256),
        ),
        migrations.AlterField(
            model_name="anuncioboib",
            name="link_pdf",
            field=models.URLField(max_length=256),
        ),
        migrations.AlterField(
            model_name="anuncioboib",
            name="link_xml",
            field=models.URLField(max_length=256),
        ),
    ]
