# Generated by Django 5.1.5 on 2025-02-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boib_scraper", "0002_alter_anuncioboib_administracion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anuncioboib",
            name="texto_completo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anuncioboib",
            name="texto_resolucion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
