# Generated by Django 5.1.5 on 2025-02-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boib_scraper", "0003_anuncioboib_texto_completo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anuncioboib",
            name="numero_url",
            field=models.IntegerField(unique=True),
        ),
    ]
