# Generated by Django 5.1.5 on 2025-02-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examinador", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregunta",
            name="justificacion",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="normativa",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="pregunta",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="respuesta1",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="respuesta2",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="respuesta3",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="respuesta4",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterModelTable(
            name="pregunta",
            table="preguntas_test",
        ),
    ]
