# Generated by Django 5.1.5 on 2025-02-02 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examinador", "0002_alter_pregunta_justificacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregunta",
            name="correcta",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ]
            ),
        ),
    ]
