# Generated by Django 5.1.5 on 2025-02-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examinador", "0004_errorreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorreport",
            name="comentario",
            field=models.TextField(blank=True, null=True),
        ),
    ]
