# Generated by Django 5.1.5 on 2025-02-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examinador", "0005_errorreport_comentario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregunta",
            name="justificacion",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="normativa",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="pregunta",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="respuesta1",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="respuesta2",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="respuesta3",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="pregunta",
            name="respuesta4",
            field=models.TextField(),
        ),
    ]
